server:
  port: 8085

spring:
  application:
    name: reservation
  profiles:
    active: dev

reservation:
  ttl-minutes: 15
  expiration:
    check-interval-ms: 600000 # 10 minutes

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "reservation"
    description: "Reservation microservice for Ingress ticketing system"
    version: "1.0.0"

logging:
  level:
    root: INFO
    com.teixaa: DEBUG
    org.springframework.kafka: INFO

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
