server:
  port: 9000
spring:
  application:
    name: events
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "events"
    description: "application of events"
    version: "1.0.0"

logging:
  level:
    root: INFO
    com.teixaa: DEBUG
    org.springframework.kafka: INFO

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
